version: "2" 

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./data/gitea:/data
    ports:
      - "9080:3000"
      - "9022:22"
  drone:
    image: drone/drone:latest
    ports:
      - "${DRONE_SERVER_GITEA_PORT-9081}:80"
    volumes:
      - ./data/drone:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - DRONE_USER_CREATE=${DRONE_USER_CREATE}
      - DRONE_SERVER_HOST=${DRONE_SERVER_GITEA_HOST}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_TLS_AUTOCERT=false
      - DRONE_RUNNER_CAPACITY=3
      # GitHub Config
      - DRONE_GITEA=true
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}
      - DRONE_GITEA_SERVER=${DRONE_GITEA_SERVER}
    links:
      - gitea
    depends_on:
      - gitea
