version: "2" 

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./data/gitea:/data
    ports:
      - "9080:3000"
      - "9022:22"
  drone:
    image: drone/drone:1.0.0-rc.3
    ports:
      - "9081:80"
    volumes:
      - ./data/drone:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - DRONE_SERVER_HOST=drone
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_RPC_SECRET=secret
      - DRONE_RUNNER_CAPACITY=3
      - DRONE_USER_CREATE=${DRONE_USER_CREATE}
      # GitHub Config
      - DRONE_GITEA=true
      - DRONE_GITEA_SERVER=http://gitea:3000
    links:
      - gitea
    depends_on:
      - gitea
